services:
  orders:
    build:
      context: ./services/orders
      dockerfile: Dockerfile
    ports:
      - "0:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@db-orders:5432/orders"
      - SERVICE_NAME=orders
    depends_on:
      - db-orders
    networks:
      - project-network
  db-orders:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
    volumes:
      - "pgdata-orders:/var/lib/postgresql/data"
    networks:
      - project-network
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    ports:
      - "0:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@db-users:5432/users"
      - SERVICE_NAME=users
    depends_on:
      - db-users
    networks:
      - project-network
  db-users:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    volumes:
      - "pgdata-users:/var/lib/postgresql/data"
    networks:
      - project-network
  products:
    build:
      context: ./services/products
      dockerfile: Dockerfile
    ports:
      - "0:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@db-products:5432/products"
      - SERVICE_NAME=products
    depends_on:
      - db-products
    networks:
      - project-network
  db-products:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products
    volumes:
      - "pgdata-products:/var/lib/postgresql/data"
    networks:
      - project-network
  payment:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    ports:
      - "0:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@db-payment:5432/payment"
      - SERVICE_NAME=payment
    depends_on:
      - db-payment
    networks:
      - project-network
  db-payment:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment
    volumes:
      - "pgdata-payment:/var/lib/postgresql/data"
    networks:
      - project-network
  reviews:
    build:
      context: ./services/reviews
      dockerfile: Dockerfile
    ports:
      - "0:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@db-reviews:5432/reviews"
      - SERVICE_NAME=reviews
    depends_on:
      - db-reviews
    networks:
      - project-network
  db-reviews:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reviews
    volumes:
      - "pgdata-reviews:/var/lib/postgresql/data"
    networks:
      - project-network
networks:
  project-network:
    driver: bridge
volumes:
  pgdata-orders:
  pgdata-users:
  pgdata-products:
  pgdata-payment:
  pgdata-reviews:
