from pydantic import BaseModel
from services.orders.domain import Order
from services.orders.application import OrderUseCase
from services.orders.infrastructure import OrderRepository
from fastapi import FastAPI
from fastapi.responses import JSONResponse
from fastapi import HTTPException
from services.orders.domain import OrderStatus
from services.orders.application import OrderUseCase
from services.orders.infrastructure import OrderRepository