from fastapi import FastAPI
from microservico-de-pedidos.application import PedidosUseCase
from microservico-de-pedidos.infrastructure import PedidosRepository
from microservico-de-pedidos.domain import PedidosEntity
from microservico-de-pedidos.application import PedidosUseCase
from microservico-de-pedidos.infrastructure import PedidosRepository
from fastapi import FastAPI
from microservico-de-pedidos.application import PedidosUseCase
from microservico-de-pedidos.infrastructure import PedidosRepository
