services:
  ifoodclone14:
    build:
      context: ./services/ifoodclone14
      dockerfile: Dockerfile
    ports:
      - "0:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@db-ifoodclone14:5432/ifoodclone14"
      - SERVICE_NAME=ifoodclone14
    depends_on:
      - db-ifoodclone14
    networks:
      - project-network
  db-ifoodclone14:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ifoodclone14
    volumes:
      - "pgdata-ifoodclone14:/var/lib/postgresql/data"
    networks:
      - project-network
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "0:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@db-auth:5432/auth"
      - SERVICE_NAME=auth
    depends_on:
      - db-auth
    networks:
      - project-network
  db-auth:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    volumes:
      - "pgdata-auth:/var/lib/postgresql/data"
    networks:
      - project-network
  payment:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    ports:
      - "0:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@db-payment:5432/payment"
      - SERVICE_NAME=payment
    depends_on:
      - db-payment
    networks:
      - project-network
  db-payment:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment
    volumes:
      - "pgdata-payment:/var/lib/postgresql/data"
    networks:
      - project-network
  shipping:
    build:
      context: ./services/shipping
      dockerfile: Dockerfile
    ports:
      - "0:8000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@db-shipping:5432/shipping"
      - SERVICE_NAME=shipping
    depends_on:
      - db-shipping
    networks:
      - project-network
  db-shipping:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shipping
    volumes:
      - "pgdata-shipping:/var/lib/postgresql/data"
    networks:
      - project-network
networks:
  project-network:
    driver: bridge
volumes:
  pgdata-ifoodclone14:
  pgdata-auth:
  pgdata-payment:
  pgdata-shipping:
